### ISSUE TITLE
2. Establishing API endpoints

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/amplify-back-end#2]
## What we're hoping to establish in March

- [x] instantiate Vue app @BeeXiong perhaps use this template with[ vue and express](https://github.com/rdxi/vue-express)?
- [x] Create heroku variables @manishapriya94 
- [x] Create accounts and set up billing @manishapriya94 
- [ ] [Postgres](https://github.com/Ally-Guide/amplify-back-end/issues/16) (priority 1)
- [x] Google Civic API  @BeeXiong 
- [x] [Auth0 ](https://github.com/Ally-Guide/amplify-back-end/projects/2#card-56832939)@BeeXiong (priority 2)
- [ ] [Twilio](https://github.com/Ally-Guide/amplify-back-end/projects/2#card-56832955) @BeeXiong  (priority 3
- [x] [Lob API ](https://github.com/Ally-Guide/amplify-back-end/issues/3)(priority 4) @BeeXiong 
- [x] Create wiki for [API functions](https://www.notion.so/Amplify-Product-Log-cb2e4e0950334349b48de25bb6b7f0ca#f1dbab0cfaaa420292b2240456d66bd5) @manishapriya94 

**Heroku environment variables for each** 
<img width="352" alt="Screen Shot 2021-03-13 at 9 03 12 AM" src="https://user-images.githubusercontent.com/9143339/111038016-a0930c00-83db-11eb-97fe-e4835d1a627b.png">

### AIRTABLE
- [API Docs](https://airtable.com/appamjI9CHzLJhPrO/api/docs#curl/introduction)
- [Reference app code in Give](https://github.com/Ally-Guide/ally-guide-app/blob/master/client/src/views/Give.vue)
- [Campaigns table in Airtable to reference](https://airtable.com/shrNsSavqMiNacQoP)
- Information to be consumed
  - Picture of org
  - Name of campaign 
  - Cause 
  - State
  - Number of letters
  - Summary 
  - org website link 
 

### GOOGLE CIVIC API
- [API Docs ](https://developers.google.com/civic-information/docs/v2/representatives)
- [Reference app code in elevate](https://github.com/Ally-Guide/ally-guide-app/blob/master/client/src/views/Amplify.vue)
- Information to be consumed
  - Rep name
  - Office division
  - address 
  - social media
  - picture 

### LOB API
- [API Docs](https://docs.lob.com/node#test-and-live-environments)
- Information to be consumed
  - template ID

**Comment by BeeXiong** [comment]
Hey @manishapriya94 and @mahrsbar. Backend has been set up but need to still configure the Airtable endpoint. I'll hopefully be able to take a look tomorrow night and add documentation as well.
