### ISSUE TITLE
Revise "volunteers" database schema to break down name and address?

### ISSUE THREAD

**Issue by JamesMGreene** [Ally-Guide/amplify-back-end#66]
Should we revise the `volunteers` database schema to break down `name` and `physical_address` columns into more granular bits? I followed what I saw in the Notion Product Log but now I've noticed that in the current production database (pre-migration), those fields were actually broken down into:

`name` ➡️  `first_name`, `last_name`
`physical_address` ➡️ `street_address` (line 1), `address_2` (line 2), `city`, `state`, `zip`

I haven't verified but I'm guessing that better aligns with what the Lob API will be expecting us to provide vs. just a large text field like I used? 😅 

:warning: Database migrations must never be revised, so we will need to create a new migration to alter and repopulate these. 👍🏻

**Comment by JamesMGreene** [comment]
Also: will a similar breakdown be necessary for representative information in the `sent_letters` table?

**Comment by manishapriya94** [comment]
Took this into consideration and added to #72
