### ISSUE TITLE
Update Amplify Endpoint to Representatives

### ISSUE THREAD

**Issue by BeeXiong** [Ally-Guide/amplify-back-end#83]
Creating a new issue to update the Amplify Endpoint. 

Per our conversation in the [Send Letter Issue](https://github.com/Ally-Guide/amplify-back-end/issues/72), updating `api/amplify/{zipcode}` to reflect `api/representatives/{zipcode}`

- [x] Modify app.js file for routing
- [x] Change name of Amplify Endpoint to Representatives
- [x] Update Wiki information to reflect Representatives
- [x] Update Front-End URL for --> @mahrsbar

**Comment by JamesMGreene** [comment]
Closed by #84 + #86
